// src/pages/OverviewPage.tsx
import { Gauge } from "lucide-react";

type OverviewPageProps = {

};

export function OverviewPage({}: OverviewPageProps) {

  return (
    <section className="grid min-h-0 flex-1 grid-cols-[minmax(0,1fr)_320px] gap-4 overflow-hidden">
      <section className="flex min-h-0 flex-1 flex-col overflow-hidden rounded-lg border border-stone-200 bg-white shadow-sm">

      </section>
      <aside className="rounded-lg border border-stone-200 bg-white p-4 shadow-sm">
        <div className="flex items-center gap-2">
          <Gauge className="h-5 w-5 text-brand" />
          <h3 className="font-bold">Top projects</h3>
        </div>
        <div className="mt-4 space-y-3">
          
        </div>
      </aside>
    </section>
  );
}

// src/features/overview/components/OverviewPage.vue
<script setup lang="ts">
</script>

<template>
  <section class="grid min-h-0 flex-1 grid-cols-[minmax(0,1fr)_320px] gap-4 overflow-hidden">
    <section class="flex min-h-0 flex-1 flex-col overflow-hidden rounded-lg border border-stone-200 bg-white shadow-sm">
    </section>
    <aside class="rounded-lg border border-stone-200 bg-white p-4 shadow-sm">
      <div class="flex items-center gap-2">
        <i class="pi pi-gauge text-xl text-brand" />
        <h3 class="font-bold">Top projects</h3>
      </div>
      <div class="mt-4 space-y-3">
      </div>
    </aside>
  </section>
</template>
